// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUEOTlBqCaOl9b2NWMlTrUtPZSsGJ8HxY',
    appId: '1:556600212060:web:77fc5f2ec4a3128c228499',
    messagingSenderId: '556600212060',
    projectId: 'flutter-firbase-a02b5',
    authDomain: 'flutter-firbase-a02b5.firebaseapp.com',
    storageBucket: 'flutter-firbase-a02b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGrsyAhgqc0Ar4uSJETletq-t1lHCTLXY',
    appId: '1:556600212060:android:e3708d7647a96bb3228499',
    messagingSenderId: '556600212060',
    projectId: 'flutter-firbase-a02b5',
    storageBucket: 'flutter-firbase-a02b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO4h4Zkv4-CkqEB1d_iq5QaReCCjy6eSc',
    appId: '1:556600212060:ios:ca9931dc9ced2b0b228499',
    messagingSenderId: '556600212060',
    projectId: 'flutter-firbase-a02b5',
    storageBucket: 'flutter-firbase-a02b5.appspot.com',
    iosBundleId: 'com.example.firebaseTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO4h4Zkv4-CkqEB1d_iq5QaReCCjy6eSc',
    appId: '1:556600212060:ios:3b8836bc03960015228499',
    messagingSenderId: '556600212060',
    projectId: 'flutter-firbase-a02b5',
    storageBucket: 'flutter-firbase-a02b5.appspot.com',
    iosBundleId: 'com.example.firebaseTutorial.RunnerTests',
  );
}
